In [2]:
import pandas as pd
import numpy as np

In [3]:
raw = pd.DataFrame({
    "name": ["Eric", "gpt", "A", "B", None],
    "age": [24, 10, None, 66, 67],
    "score": [430, None, 56, 16.6, None],
    "city": ["1", "2", None, "4", "5"]
})
raw

   name   age  score  city
0  Eric  24.0  430.0     1
1   gpt  10.0    NaN     2
2     A   NaN   56.0  None
3     B  66.0   16.6     4
4  None  67.0    NaN     5

In [4]:
raw.isna().sum()

name     1
age      1
score    2
city     1
dtype: int64

In [5]:
raw["score"] = raw["score"].fillna(raw['score'].mean())
raw

   name   age       score  city
0  Eric  24.0  430.000000     1
1   gpt  10.0  167.533333     2
2     A   NaN   56.000000  None
3     B  66.0   16.600000     4
4  None  67.0  167.533333     5

In [6]:
raw["city"] = raw["city"].fillna(0)
raw["city"] = raw["city"].astype(int)
print(raw.dtypes)
raw

name      object
age      float64
score    float64
city       int64
dtype: object

   name   age       score  city
0  Eric  24.0  430.000000     1
1   gpt  10.0  167.533333     2
2     A   NaN   56.000000     0
3     B  66.0   16.600000     4
4  None  67.0  167.533333     5

In [7]:
result = raw[(raw["age"] > 20) & (raw["score"] > raw["score"].mean())]
result

   name   age  score  city
0  Eric  24.0  430.0     1

In [8]:
raw.sort_values(by = "score" , ascending=False)

   name   age       score  city
0  Eric  24.0  430.000000     1
1   gpt  10.0  167.533333     2
4  None  67.0  167.533333     5
2     A   NaN   56.000000     0
3     B  66.0   16.600000     4

In [9]:
raw["status"] = np.where(raw["score"] >= 60 , "Pass" , "Fail")
raw

   name   age       score  city status
0  Eric  24.0  430.000000     1   Pass
1   gpt  10.0  167.533333     2   Pass
2     A   NaN   56.000000     0   Fail
3     B  66.0   16.600000     4   Fail
4  None  67.0  167.533333     5   Pass

In [10]:
fill_values = {"name":"Anonymous" , "age":raw["age"].median()}
raw = raw.fillna(value = fill_values)
raw

        name   age       score  city status
0       Eric  24.0  430.000000     1   Pass
1        gpt  10.0  167.533333     2   Pass
2          A  45.0   56.000000     0   Fail
3          B  66.0   16.600000     4   Fail
4  Anonymous  67.0  167.533333     5   Pass

In [11]:
raw.groupby("status")["age"].mean()

status
Fail    55.500000
Pass    33.666667
Name: age, dtype: float64

In [12]:
raw = raw.round({"age":0 , "score":1})
raw

        name   age  score  city status
0       Eric  24.0  430.0     1   Pass
1        gpt  10.0  167.5     2   Pass
2          A  45.0   56.0     0   Fail
3          B  66.0   16.6     4   Fail
4  Anonymous  67.0  167.5     5   Pass

In [13]:
raw = raw.rename(columns = {"name":"姓名" , "score":"成績"})
raw

          姓名   age     成績  city status
0       Eric  24.0  430.0     1   Pass
1        gpt  10.0  167.5     2   Pass
2          A  45.0   56.0     0   Fail
3          B  66.0   16.6     4   Fail
4  Anonymous  67.0  167.5     5   Pass

In [14]:
raw.to_csv("cleaned_data.csv", index=False)