In [43]:
import pandas as pd

In [44]:
df = pd.DataFrame({
    "name": ["Eric", "gpt", "A", "B", "C"],
    "age": ["24", "10", "65", "66", "67"],
    "score": [420, 100, 0.56, 6.6, 76],
    "city": ["1", "2", "3", "4", "5"]
})
df

   name age   score city
0  Eric  24  420.00    1
1   gpt  10  100.00    2
2     A  65    0.56    3
3     B  66    6.60    4
4     C  67   76.00    5

In [45]:
df.head()

   name age   score city
0  Eric  24  420.00    1
1   gpt  10  100.00    2
2     A  65    0.56    3
3     B  66    6.60    4
4     C  67   76.00    5

In [46]:
df.info()
print("=========================================")
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      object
 2   score   5 non-null      float64
 3   city    5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes
=========================================

            score
count    5.000000
mean   120.632000
std    172.814551
min      0.560000
25%      6.600000
50%     76.000000
75%    100.000000
max    420.000000

In [47]:
df["name"]
df[["name", "score"]]

   name   score
0  Eric  420.00
1   gpt  100.00
2     A    0.56
3     B    6.60
4     C   76.00

In [48]:
df[df["score"] > 60]

   name age  score city
0  Eric  24  420.0    1
1   gpt  10  100.0    2
4     C  67   76.0    5

In [49]:
df.sort_values(by="score", ascending=False)

   name age   score city
0  Eric  24  420.00    1
1   gpt  10  100.00    2
4     C  67   76.00    5
3     B  66    6.60    4
2     A  65    0.56    3

In [50]:
df.sort_values(by="age")

   name age   score city
1   gpt  10  100.00    2
0  Eric  24  420.00    1
2     A  65    0.56    3
3     B  66    6.60    4
4     C  67   76.00    5

In [51]:
df["pass"] = df["score"] >= 60
df

   name age   score city   pass
0  Eric  24  420.00    1   True
1   gpt  10  100.00    2   True
2     A  65    0.56    3  False
3     B  66    6.60    4  False
4     C  67   76.00    5   True

In [52]:
df.loc[2, "score"] = 80

df

   name age  score city   pass
0  Eric  24  420.0    1   True
1   gpt  10  100.0    2   True
2     A  65   80.0    3  False
3     B  66    6.6    4  False
4     C  67   76.0    5   True

In [53]:
df["score"] = df["score"] + 10
df

   name age  score city   pass
0  Eric  24  430.0    1   True
1   gpt  10  110.0    2   True
2     A  65   90.0    3  False
3     B  66   16.6    4  False
4     C  67   86.0    5   True

In [54]:
df.drop(columns=["city"], inplace=True)
df

   name age  score   pass
0  Eric  24  430.0   True
1   gpt  10  110.0   True
2     A  65   90.0  False
3     B  66   16.6  False
4     C  67   86.0   True

In [55]:
df.drop(index=3, inplace=True)
df

   name age  score   pass
0  Eric  24  430.0   True
1   gpt  10  110.0   True
2     A  65   90.0  False
4     C  67   86.0   True

In [56]:
df2 = pd.DataFrame({
    "name": ["Eric", "gpt", "A", "B", "C"],
    "level": ["S", "A", "A", "B", "C"]
})
df2

   name level
0  Eric     S
1   gpt     A
2     A     A
3     B     B
4     C     C

In [57]:
merged = pd.merge(df, df2, on="name")
merged

   name age  score   pass level
0  Eric  24  430.0   True     S
1   gpt  10  110.0   True     A
2     A  65   90.0  False     A
3     C  67   86.0   True     C

In [58]:
merged.groupby("level")["score"].mean()

level
A    100.0
C     86.0
S    430.0
Name: score, dtype: float64

In [59]:
merged.groupby("level")["score"].agg(["mean", "max", "min"])

        mean    max    min
level
A      100.0  110.0   90.0
C       86.0   86.0   86.0
S      430.0  430.0  430.0

In [60]:
merged.groupby("level")["pass"].mean()

level
A    0.5
C    1.0
S    1.0
Name: pass, dtype: float64